{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
  namespace: {{ .Values.clusterRole.namespace }}
  labels:
    {{- include "egagent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
 annotations:
   {{- toYaml . | nindent 4 }}
 {{- end }}
rules:
- nonResourceURLs:
    - "/version"
    - "/healthz"
    - "/metrics"
  verbs: ["get"]
  apiGroups: []
  resources: []
- apiGroups: ["batch"]
  resources:
    - "jobs"
    - "cronjobs"
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
    - "deployments"
    - "replicasets"
    - "ingresses"
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - "deployments"
    - "replicasets"
    - "daemonsets"
    - "statefulsets"
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - "namespaces"
    - "events"
    - "services"
    - "endpoints"
    - "nodes"
    - "nodes/log"
    - "nodes/metrics"
    - "nodes/proxy"
    # - "nodes/spec"
    - "nodes/stats"
    - "pods"
    - "replicationcontrollers"
    - "componentstatuses"
    - "resourcequotas"
    - "persistentvolumes"
    - "persistentvolumeclaims"
    - "limitranges"
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
    - "pods"
    - "nodes"
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
    - "horizontalpodautoscalers"
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources:
    - "leases"
  verbs: ["get", "list", "watch"]
# - apiGroups: [""]
  # resources:
    # - "endpoints"
  # verbs: ["create", "update", "patch"]
# - apiGroups: ["networking.k8s.io"]
  # resources:
    # - "ingresses"
  # verbs: ["get", "list", "watch"]
- apiGroups: ["apps.openshift.io"]
  resources:
    - "deploymentconfigs"
  verbs: ["get", "list", "watch"]
- apiGroups: ["security.openshift.io"]
  resourceNames: ["privileged"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
- apiGroups: ["config.openshift.io"]
  resources:
    - "clusteroperators"
  verbs: ["get", "list", "watch"]

{{- end }}
