{{- if .Values.userSSLCertsSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: egagent-ssl-certs
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
type: Opaque
{{- with .Values.userSSLCertsSecret.data }}
data:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
---
{{- if .Values.agentJreCacertsSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: egagent-jre-cacerts
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
type: Opaque
{{- with .Values.agentJreCacertsSecret.data }}
data:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}